pool: Default
trigger:
  - main
jobs:
  - job: dotnet
    displayName: dotnet
    steps:
          - task: DotNetCoreCLI@2
            inputs: 
              command: 'restore'
              projects: ./MusicStore/MusicStore.csproj
          - task: DotNetCoreCLI@2
            inputs: 
              command: 'build'
              projects: ./MusicStore/MusicStore.csproj
              
          - task: DotNetCoreCLI@2
            inputs: 
              command: 'test'
              projects: ./MusicStore/MusicStore.csproj
              publishTestResults: true
          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '**/*.csproj'
              arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
              zipAfterPublish: true
              modifyOutputPath: true
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: /home/ubuntu/myagent/_work/1/s/MusicStore/ClientApp
          - task: Npm@1
            inputs: 
              command: 'custom'
              customCommand: ' build'
              workingDir: /home/ubuntu/myagent/_work/1/s/MusicStore/ClientApp



      